const projectsData = [
  {
    id: 1,
    title: "Full-Stack E-Commerce Platform: Evie & Co.",
    date: "2024-10-02",
    github:
      "https://github.com/AlrightErin27/erinvb-portfolio-2024/tree/main/src/Components/Shop",
    url: "www.erinvanbrunt.com/shop",
    videoUrl: "https://player.vimeo.com/video/1020451588",
    notes:
      "Developed a comprehensive e-commerce solution utilizing React.js for the frontend and Node.js with Express.js for the backend, integrated with MongoDB. This full-stack application showcases proficiency in creating scalable, secure web applications with robust state management and RESTful API integration.",
    techUsed: [
      "Axios",
      "Bcrypt",
      "CSS Grid",
      "Component Architecture",
      "Cors",
      "Dotenv",
      "Express.js",
      "Flex-box",
      "Git",
      "JWT Authentication",
      "LocalStorage",
      "Media queries",
      "MongoDB",
      "Mongoose",
      "Node.js",
      "Postman",
      "RESTful API Design",
      "React Hooks (useState, useEffect, useCallback, useRef)",
      "React Router for navigation",
      "React.js",
      "Responsive CSS3",
      "Responsive design principles",
      "Secure Routing",
      "State Management",
    ],
  },
  {
    id: 2,
    title: "Cemetery Run: Retro-Inspired Arcade Game",
    date: "2024-10-14",
    github:
      "https://github.com/AlrightErin27/erinvb-portfolio-2024/tree/main/src/Components/Games/CemeteryRun",
    url: "www.erinvanbrunt.com/games/cemetery-run",
    videoUrl: "https://player.vimeo.com/video/1021123280",
    notes:
      "Engineered an engaging endless runner game inspired by classic arcade titles, leveraging React.js and HTML5 Canvas. The game features a unique retro-pixel aesthetic with a Halloween theme, demonstrating proficiency in game logic implementation, custom hook development, and audio integration within a React environment.",
    techUsed: [
      "Audio API Integration",
      "CSS Animation",
      "Custom React Hooks",
      "Game State Management",
      "HTML5 Canvas",
      "Keyboard Event Handling",
      "Performance Optimization",
      "Pixel Art Design",
      "React.js",
      "Responsive Web Design",
      "Web Audio API",
      "CSS Variables",
      "Flexbox Layout",
      "Media Queries",
      "CSS Pseudo-elements",
      "requestAnimationFrame for smooth animations",
      "Collision Detection (AABB)",
      "Dynamic Difficulty Scaling",
      "Asset Preloading",
      "Touch Event Handling",
      "CSS Box-shadow for visual effects",
      "Base64 Encoded Images",
      "ES6+ JavaScript Features",
      "Asynchronous JavaScript (Promises, async/await)",
      "React useEffect, useState, useRef, and useCallback Hooks",
      "CSS Clamp() function for responsive typography",
      "Event Bubbling Prevention",
      "Accessibility Considerations (ARIA labels)",
    ],
  },
  {
    id: 3,
    title: "Dynamic Blog Content Integration",
    date: "2024-09-20",
    github:
      "https://github.com/AlrightErin27/erinvb-portfolio-2024/tree/main/src/Components/Blog",
    url: "www.erinvanbrunt.com/blog",
    videoUrl: "https://player.vimeo.com/video/1020009691",
    notes:
      "Implemented a dynamic blog integration system that fetches and displays content from Medium using Axios and the RSS2JSON API. This project showcases proficiency in working with external APIs, asynchronous JavaScript, and creating responsive layouts for optimal content presentation.",
    techUsed: [
      "Asynchronous JavaScript",
      "Axios",
      "CSS Grid/Flex-box",
      "CSS Keyframes Animation",
      "Content Optimization",
      "Error Handling",
      "External API Integration",
      "Fetch",
      "JSX",
      "Postman",
      "RSS2JSON API",
      "React.js",
      "Responsive Design",
      "State Management",
    ],
  },
  {
    id: 4,
    title: "Interactive Buffy-Themed Crossword Puzzle",
    date: "2024-08-20",
    github:
      "https://github.com/AlrightErin27/erinvb-portfolio-2024/tree/main/src/Components/Games/Crossword",
    url: "www.erinvanbrunt.com/games/crossword",
    videoUrl: "https://example.com/video4.mp4",
    notes:
      "Designed and developed an interactive crossword puzzle game themed around 'Buffy the Vampire Slayer'. This React-based application demonstrates advanced state management, custom keyboard navigation, and responsive design principles, providing a seamless user experience across various devices.",
    techUsed: [
      "Accessibility Features",
      "Advanced State Management",
      "CSS Grid",
      "Cross-browser Compatibility",
      "Custom Keyboard Navigation",
      "Local Storage Integration",
      "Mouse Event Handling",
      "React.js",
      "Responsive Web Design",
    ],
  },
  {
    id: 5,
    title: "Tarot Card Concentration Game",
    date: "2024-08-10",
    github:
      "https://github.com/AlrightErin27/erinvb-portfolio-2024/tree/main/src/Components/Games/Concentration",
    url: "www.erinvanbrunt.com/games/concentration",
    videoUrl: "https://player.vimeo.com/video/1020412279",
    notes:
      "Crafted an engaging memory game featuring Tarot card imagery, built with React.js and enhanced with ReactCardFlip for smooth animations. This project showcases the implementation of complex game logic, state management, and the integration of third-party libraries to create an immersive user experience.",
    techUsed: [
      "Accessibility Considerations",
      "Asset Preloading",
      "CSS3 Animations",
      "Custom Hooks",
      "Performance Optimization",
      "React.js",
      "ReactCardFlip",
      "Responsive Layout",
      "State Management",
    ],
  },
  {
    id: 6,
    title: "Modern Tic-Tac-Toe with React",
    date: "2024-07-29",
    github:
      "https://github.com/AlrightErin27/erinvb-portfolio-2024/tree/main/src/Components/Games/NoughtsAndCrosses",
    url: "www.erinvanbrunt.com/games/noughts-&-crosses",
    videoUrl: "https://player.vimeo.com/video/1019997466",
    notes:
      "Developed a visually striking implementation of the classic Tic-Tac-Toe game using React.js. The application features a dark floral background with a high-contrast UI, demonstrating proficiency in creating aesthetically pleasing and functional web applications with attention to user experience and design principles.",
    techUsed: [
      "CSS-in-JS",
      "Conditional Rendering",
      "Game Logic Implementation",
      "React.js",
      "Responsive Design",
      "State Management",
      "UI/UX Best Practices",
    ],
  },
  {
    id: 7,
    title: "Jungle Tetris: React-Redux Arcade Game",
    date: "2022-07-01",
    github:
      "https://github.com/AlrightErin27/erinvb-portfolio/tree/main/src/components/Games/Tetris",
    url: "",
    videoUrl: "https://player.vimeo.com/video/741488052",
    notes:
      "Developed an immersive Tetris-inspired game with a jungle theme using React and Redux. This project demonstrates advanced state management techniques, custom hook implementation, and dynamic layout creation using CSS Grid. The game features responsive design, custom styling, and integrates complex game logic with smooth user interactions.",
    techUsed: [
      "CSS Grid",
      "Cross-browser Compatibility",
      "Custom React Hooks",
      "Game State Management",
      "Git Version Control",
      "JavaScript ES6+",
      "Performance Optimization",
      "React.js",
      "Redux",
      "Responsive Design",
    ],
  },
  {
    id: 8,
    title: "The Castle Shop: Full-Stack E-Commerce Platform",
    date: "2022-01-01",
    github: "https://github.com/AlrightErin27/castlesFI",
    url: "",
    videoUrl: "https://player.vimeo.com/video/741486139",
    notes:
      "Developed a comprehensive e-commerce platform for castle enthusiasts using Ruby on Rails for the backend and React for the frontend. This full-stack application showcases the integration of complex database relationships with Active Record, demonstrating proficiency in RESTful API design and efficient state management. The project features secure user authentication using OAuth and bcrypt, a robust shopping cart system, and an intuitive product browsing experience, highlighting skills in both server-side and client-side web development.",
    techUsed: [
      "Active Record",
      "Component-based Architecture",
      "Git Version Control",
      "Heroku Deployment",
      "OAuth",
      "PostgreSQL",
      "RESTful API Design",
      "React.js",
      "Redux for State Management",
      "Responsive CSS",
      "Ruby on Rails",
      "bcrypt",
    ],
  },
];

export default projectsData;
