const projectsData = [
  {
    id: 1,
    title: "Full-Stack E-Commerce Platform: Evie & Co.",
    date: "2024-10-02",
    github:
      "https://github.com/AlrightErin27/erinvb-portfolio-2024/tree/main/src/Components/Shop",
    url: "www.erinvanbrunt.com/shop",
    videoUrl: "https://example.com/video1.mp4",
    notes:
      "Developed a comprehensive e-commerce solution utilizing React.js for the frontend and Node.js with Express.js for the backend, integrated with MongoDB. This full-stack application showcases proficiency in creating scalable, secure web applications with robust state management and RESTful API integration.",
    techUsed: [
      "React.js",
      "Node.js",
      "Express.js",
      "MongoDB",
      "RESTful API Design",
      "JWT Authentication",
      "State Management",
      "Responsive CSS",
      "Component Architecture",
      "Secure Routing",
    ],
  },
  {
    id: 2,
    title: "Cemetery Run: Retro-Inspired Arcade Game",
    date: "2024-10-14",
    github:
      "https://github.com/AlrightErin27/erinvb-portfolio-2024/tree/main/src/Components/Games/CemeteryRun",
    url: "www.erinvanbrunt.com/games/cemetery-run",
    videoUrl: "https://example.com/video6.mp4",
    notes:
      "Engineered an engaging endless runner game inspired by classic arcade titles, leveraging React.js and HTML5 Canvas. The game features a unique retro-pixel aesthetic with a Halloween theme, demonstrating proficiency in game logic implementation, custom hook development, and audio integration within a React environment.",
    techUsed: [
      "React.js",
      "HTML5 Canvas",
      "Custom React Hooks",
      "Game State Management",
      "Audio API Integration",
      "Keyboard Event Handling",
      "CSS Animation",
      "Pixel Art Design",
      "Performance Optimization",
    ],
  },
  {
    id: 3,
    title: "Dynamic Blog Content Integration",
    date: "2024-09-20",
    github:
      "https://github.com/AlrightErin27/erinvb-portfolio-2024/tree/main/src/Components/Blog",
    url: "www.erinvanbrunt.com/blog",
    videoUrl: "https://example.com/video2.mp4",
    notes:
      "Implemented a dynamic blog integration system that fetches and displays content from Medium using Axios and the RSS2JSON API. This project showcases proficiency in working with external APIs, asynchronous JavaScript, and creating responsive layouts for optimal content presentation.",
    techUsed: [
      "React.js",
      "Axios",
      "External API Integration",
      "Asynchronous JavaScript",
      "State Management",
      "Error Handling",
      "Responsive Design",
      "CSS Grid/Flexbox",
      "Pagination",
      "Content Optimization",
    ],
  },
  {
    id: 4,
    title: "Interactive Buffy-Themed Crossword Puzzle",
    date: "2024-08-20",
    github:
      "https://github.com/AlrightErin27/erinvb-portfolio-2024/tree/main/src/Components/Games/Crossword",
    url: "www.erinvanbrunt.com/games/crossword",
    videoUrl: "https://example.com/video4.mp4",
    notes:
      "Designed and developed an interactive crossword puzzle game themed around 'Buffy the Vampire Slayer'. This React-based application demonstrates advanced state management, custom keyboard navigation, and responsive design principles, providing a seamless user experience across various devices.",
    techUsed: [
      "React.js",
      "Advanced State Management",
      "Custom Keyboard Navigation",
      "Mouse Event Handling",
      "Responsive Web Design",
      "CSS Grid",
      "Local Storage Integration",
      "Accessibility Features",
      "Cross-browser Compatibility",
    ],
  },
  {
    id: 5,
    title: "Tarot Card Concentration Game",
    date: "2024-08-10",
    github:
      "https://github.com/AlrightErin27/erinvb-portfolio-2024/tree/main/src/Components/Games/Concentration",
    url: "www.erinvanbrunt.com/games/concentration",
    videoUrl: "https://example.com/video3.mp4",
    notes:
      "Crafted an engaging memory game featuring Tarot card imagery, built with React.js and enhanced with ReactCardFlip for smooth animations. This project showcases the implementation of complex game logic, state management, and the integration of third-party libraries to create an immersive user experience.",
    techUsed: [
      "React.js",
      "ReactCardFlip",
      "Custom Hooks",
      "State Management",
      "CSS3 Animations",
      "Responsive Layout",
      "Performance Optimization",
      "Asset Preloading",
      "Accessibility Considerations",
    ],
  },
  {
    id: 6,
    title: "Modern Tic-Tac-Toe with React",
    date: "2024-07-29",
    github:
      "https://github.com/AlrightErin27/erinvb-portfolio-2024/tree/main/src/Components/Games/NoughtsAndCrosses",
    url: "www.erinvanbrunt.com/games/noughts-&-crosses",
    videoUrl: "https://example.com/video5.mp4",
    notes:
      "Developed a visually striking implementation of the classic Tic-Tac-Toe game using React.js. The application features a dark floral background with a high-contrast UI, demonstrating proficiency in creating aesthetically pleasing and functional web applications with attention to user experience and design principles.",
    techUsed: [
      "React.js",
      "State Management",
      "Conditional Rendering",
      "CSS-in-JS",
      "Responsive Design",
      "Game Logic Implementation",
      "UI/UX Best Practices",
      "Performance Optimization",
      "Cross-browser Testing",
    ],
  },
  {
    id: 7,
    title: "Jungle Tetris: React-Redux Arcade Game",
    date: "2022-07-01",
    github:
      "https://github.com/AlrightErin27/erinvb-portfolio/tree/main/src/components/Games/Tetris",
    url: "",
    videoUrl: "https://player.vimeo.com/video/741488052",
    notes:
      "Developed an immersive Tetris-inspired game with a jungle theme using React and Redux. This project demonstrates advanced state management techniques, custom hook implementation, and dynamic layout creation using CSS Grid. The game features responsive design, custom styling, and integrates complex game logic with smooth user interactions.",
    techUsed: [
      "React.js",
      "Redux",
      "Custom React Hooks",
      "CSS Grid",
      "Responsive Design",
      "Game State Management",
      "JavaScript ES6+",
      "Git Version Control",
      "Performance Optimization",
      "Cross-browser Compatibility",
    ],
  },
  {
    id: 8,
    title: "The Castle Shop: Full-Stack E-Commerce Platform",
    date: "2022-01-01",
    github: "https://github.com/AlrightErin27/castlesFI",
    url: "",
    videoUrl: "https://player.vimeo.com/video/741486139",
    notes:
      "Developed a comprehensive e-commerce platform for castle enthusiasts using Ruby on Rails for the backend and React for the frontend. This full-stack application showcases the integration of complex database relationships with Active Record, demonstrating proficiency in RESTful API design and efficient state management. The project features secure user authentication using OAuth and bcrypt, a robust shopping cart system, and an intuitive product browsing experience, highlighting skills in both server-side and client-side web development.",
    techUsed: [
      "Ruby on Rails",
      "React.js",
      "PostgreSQL",
      "Active Record",
      "RESTful API Design",
      "OAuth",
      "bcrypt",
      "Redux for State Management",
      "Responsive CSS",
      "Component-based Architecture",
      "Git Version Control",
      "Heroku Deployment",
    ],
  },
];

export default projectsData;
